# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42325e93002915d18f3c78ceaceb04c87138820bb7f614af1b93c0b7076f33547ee1f0793d3167435c01ad92dca61c9ba628b296fc8eeb69977e8a2b64055caf

test:
  secret_key_base: 141049df38962977dcf5db12aa0f315f67b823fc5afc498b629ce10f85609aa9d210abf1359d83a651cf2826aed5bb945984eea75a4c91b4f49663b51b58ade8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
